/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NyanBar
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var NyanBar = class extends import_obsidian.Plugin {
  async onload() {
    const renderBar = (el, completionPercentage, catType) => {
      let div = el.createEl("div");
      div.addClass("divCont");
      let rainbowCont = div.createEl("div");
      if (catType === "nyan") {
        rainbowCont.addClass("rainbowNyan");
      } else if (catType === "pusheen") {
        rainbowCont.addClass("rainbowPusheen");
      }
      rainbowCont.style.width = completionPercentage + "%";
      let catImg = div.createEl("img");
      catImg.addClass("img" + catType.charAt(0).toUpperCase() + catType.slice(1));
      let txt = el.createEl("h4");
      txt.textContent = completionPercentage + "%";
      txt.addClass("txt");
      if (completionPercentage < 5) {
        catImg.addClass(catType + "Transform1");
        catImg.removeClass(catType + "Transform2");
      } else {
        catImg.addClass(catType + "Transform2");
        catImg.removeClass(catType + "Transform1");
      }
    };
    this.registerMarkdownCodeBlockProcessor("nyanbar", async (source, el, ctx) => {
      const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (!markdownView)
        return;
      let completionPercentage = 0;
      if (source.trim() === "auto") {
        const checkboxes = markdownView.contentEl.querySelectorAll('input[type="checkbox"]');
        const totalCheckboxes = checkboxes.length;
        let checkedCount = 0;
        checkboxes.forEach((checkbox) => {
          if (checkbox.checked) {
            checkedCount++;
          }
        });
        completionPercentage = totalCheckboxes > 0 ? Math.round(checkedCount / totalCheckboxes * 100) : 0;
      } else {
        if (parseInt(source.trim()) >= 0 && parseInt(source.trim()) <= 100) {
          completionPercentage = Math.min(100, Math.max(0, Number(source.trim())));
        } else {
          el.createEl("h4", { text: "[ERROR: Invalid Value]" }).addClass("e");
          el.createEl("p", { text: "NYANBAR-ERROR" }).addClass("e1");
          return;
        }
      }
      renderBar(el, completionPercentage, "nyan");
    });
    this.registerMarkdownCodeBlockProcessor("pusheenbar", async (source, el, ctx) => {
      const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (!markdownView)
        return;
      let completionPercentage = 0;
      if (source.trim() === "auto") {
        const checkboxes = markdownView.contentEl.querySelectorAll('input[type="checkbox"]');
        const totalCheckboxes = checkboxes.length;
        let checkedCount = 0;
        checkboxes.forEach((checkbox) => {
          if (checkbox.checked) {
            checkedCount++;
          }
        });
        completionPercentage = totalCheckboxes > 0 ? Math.round(checkedCount / totalCheckboxes * 100) : 0;
      } else {
        if (parseInt(source.trim()) >= 0 && parseInt(source.trim()) <= 100) {
          completionPercentage = Math.min(100, Math.max(0, Number(source.trim())));
        } else {
          el.createEl("h4", { text: "[ERROR: Invalid Value]" }).addClass("e");
          el.createEl("p", { text: "PUSHEENBAR-ERROR" }).addClass("e1");
          return;
        }
      }
      renderBar(el, completionPercentage, "pusheen");
    });
    this.addCommand({
      id: "nyan",
      name: "Add a nyan cat bar",
      editorCallback: (editor) => {
        editor.setLine(editor.getCursor().line, "```nyanbar\nauto\n```");
      }
    });
    this.addCommand({
      id: "pusheen",
      name: "Add a pusheen cat bar",
      editorCallback: (editor) => {
        editor.setLine(editor.getCursor().line, "```pusheenbar\nauto\n```");
      }
    });
  }
};


/* nosourcemap */